name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Extraer el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t mi-app-react:latest .

      # Paso 4: Etiquetar la imagen para Docker Hub
      - name: Tag Docker image
        run: docker tag mi-aplicacion-react:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mi-app-react:latest

      # Paso 5: Publicar la imagen en Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mi-app-react:latest
