name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Extraer el código del repositorio
      - name: 
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 
          password: 

      # Paso 3: Construir la imagen Docker
      - name: 
        run: 

      # Paso 4: Etiquetar la imagen para Docker Hub
      - name: 
        run: 

      # Paso 5: Publicar la imagen en Docker Hub
      - name: 
        run: 